### ISSUE TITLE
Meta tag support

### ISSUE THREAD

**Issue by bcardarella** [BeaconCMS/beacon#119]
We have layout meta tags but we also need per-page meta tags.

The app should essentially do a `Map.merge` on three sets of Meta tags:

1. site-wide - these are default tags that we always want to render unless there are higher priority overlapping tags
2. layout
3. page

On each page render we first get the Map of site tags, then merge the layout tags, then the page tags. Tags are considered unique based upon the `element` name and `id_key_name` and `id_key_value`. For example:

`<meta name="foorbar" content"abc">` and `<meta name="foobar" content="def">`. In this case they conflict and the later will overwrite the former.

`<meta name="foobar" content="abc">` and `<meta name="barbaz" content="def">` these do not conflict and will both render

`<meta name="foobar" content="abc">` and `<link name="foobar" content="def">` these do not conflict and will both render

`<meta name="foobar" content="abc">` and `<meta property="foobar" content="def">` these do not conflict and will both render

Some meta tags deviate from `name` being the `id_key`. For example, both are valid meta tags:

`<meta name="foobar" content="...">` and `<meta property="foobar"  content="...">` the `key` name needs to be accounted for. The data model could probably be:

`%{element: "meta", id_key: "name", id_key_value: "foobar", content_key: "content", content_value: "..."}`

**Comment by bcardarella** [comment]
FWIW I think `<title>` should probably be included in this

**Comment by leandrocp** [comment]
Hey @bcardarella per-page meta tags were implemented on the PR https://github.com/BeaconCMS/beacon/pull/109

From your description, we're currently missing:
1. site-wide meta tags
2. merge

We would move these default meta tags to `site.meta_tags` https://github.com/BeaconCMS/beacon/blob/c7f735f9b764dc0b136aa9a32d4901a80df91942/lib/beacon_web/components/layouts/runtime.html.heex#L4-L6 So every new site would bring a set of default meta tags that can be replaced on the layout or page level. Note that `<meta name="csrf-token" content={get_csrf_token()} />` is a special case that can't be replaced nor removed.

And then implement a `meta_tags(assigns)` function where we merge site-wide meta tags with layouts and pages as you described, ie: these lines would call `meta_tags(assigns)` to fetch and merge the 3 levels of meta tags: https://github.com/BeaconCMS/beacon/blob/c7f735f9b764dc0b136aa9a32d4901a80df91942/lib/beacon_web/components/layouts/runtime.html.heex#L8-L9

To find unique meta tags on merging, as the [spec](https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element) goes "Exactly one of the name, http-equiv, charset, and itemprop attributes must be specified." so we could do a simple lookup by these keys. I'm not sure about `property="foobar"` though. I don't recall that attr being valid or I'm missing something 🤔 

Regarding `<title>` I'd like to handle it separately because it's not a meta tag and it does behave differently, we may provide a callback where users can define it dynamically based on current site/layout/page or page assigns. Some work has already started here https://github.com/BeaconCMS/beacon/issues/117

**Comment by bcardarella** [comment]
The `property="foobar"` is used by OpenGraph tags: https://ahrefs.com/blog/open-graph-meta-tags/

I'm OK handling `<title>` outside of this as I forgot its in the actual element content, not an attr

**Comment by optikfluffel** [comment]
@leandrocp 
> I'm not sure about property="foobar" though. I don't recall that attr being valid or I'm missing something 🤔

At least [Open Graph uses the `property` attribute](https://ogp.me/#metadata).

**Comment by leandrocp** [comment]
Thanks for the link @bcardarella and @optikfluffel. Ok sounds good we can account for that attr on the merging logic too.

**Comment by bcardarella** [comment]
The datamodel I outlined was mostly for flexibility. AFAIK just `name` and `property` are used in the wild. But I'm sure at some point someone may want something different.

**Comment by leandrocp** [comment]
> The datamodel I outlined was mostly for flexibility. AFAIK just `name` and `property` are used in the wild. But I'm sure at some point someone may want something different.

The current data model is a key value map as `name => content`, eg: https://github.com/BeaconCMS/beacon/blob/c7f735f9b764dc0b136aa9a32d4901a80df91942/dev.exs#L118

So we definitely need to make it more flexible to support `property` and the others.

**Comment by dukeweezo** [comment]
Hey, I'd be happy to jump on this issue!

**Comment by leandrocp** [comment]
> Hey, I'd be happy to jump on this issue!

A PR is very welcome!

**Comment by dukeweezo** [comment]
Hi an update and a few notes.

- I am handling overriding the default sitewide meta tags with an additional field in both `Layout` and `Page` called `site_meta_tags`. (If both are set I'm considering page taking precedence). This way the default site tags (provided as a `__site_meta_tags__` assign in `page_live.ex` right now) are included, unless specifically overridden.
- Default sitewide tags are the meta tags in `runtime.html.heex`, but as mentioned, `<meta name="csrf-token" content={get_csrf_token()} />` is not overridable. 
- I currently have three usable functions, `<%= site_meta_tags(assigns) %>`, `<%= layout_meta_tags(assigns) %>`, `<%= page_meta_tags(assigns) %>`, (with merging / overriding / precedence logic similar to description in the first post, and that I'll document in PR).

Let me if there are thoughts / questons / requests about any of that.

**Comment by leandrocp** [comment]
Hi @dukeweezo thanks for the update.

> default sitewide meta tags with an additional field in both Layout and Page called site_meta_tags

The default sitewide meta tags are static so you can define them in a function in the `Beacon` module: https://github.com/BeaconCMS/beacon/blob/3653c461e45c8f46ec8e1f5eef2351d095743231/lib/beacon/beacon.ex

Items 2 sounds good.

> I currently have three usable functions

Maybe you can simplify and have just 1 function `meta_tags(assigns)` and there apply all the logic to return the meta tags for the current page.

Also feel free to open a Draft PR if you wanna show some code :)

**Comment by bcardarella** [comment]
Looking over the opengraph spec: https://ogp.me/#array

It looks like you can have multiple tags of the same values. The first to appear has higher precedence. This would make implementation less complex

**Comment by dukeweezo** [comment]
> The default sitewide meta tags are static so you can define them in a function in the Beacon module: https://github.com/BeaconCMS/beacon/blob/3653c461e45c8f46ec8e1f5eef2351d095743231/lib/beacon/beacon.ex

Perfect! That's a way better place for it.

> Maybe you can simplify and have just 1 function meta_tags(assigns) and there apply all the logic to return the meta tags for the current page.

I was thinking about that, but I realized with three functions the order of the tags could be controlled at user level (or one or all could be omitted). On reflection, not sure if there's any strong reason for either of those things though

> Looking over the opengraph spec: https://ogp.me/#array

> It looks like you can have multiple tags of the same values. The first to appear has higher precedence. This would make implementation less complex

Ah yeah that would have made it way simpler. I have actually done most of the merging logic already though.

I should have a PR draft to review sometime tomorrow. 🙂
