### ISSUE TITLE
Core -> Webfiles and Metatags: Schema.org tags

### ISSUE THREAD

**Issue by bcardarella** [BeaconCMS/beacon#122]
See https://github.com/BeaconCMS/beacon/issues/122#issuecomment-1534982874 for implementation details.

---

In addition to the meta tag support we should be using schema.org tags for better SEO. Here is what dockyard.com is currently rendering:

```html
  <script id="ember899" class="ember-view" type="application/ld+json">{
  "@type": "Blog",
  "name": "DockYard Insights - DockYard Blog",
  "url": "https://dockyard.com/blog",
  "copyrightYear": 2023,
  "publisher": {
    "@type": "Corporation",
    "name": "DockYard",
    "url": "https://dockyard.com",
    "legalName": "DockYard, Inc."
  },
  "@context": "http://schema.org"
}
</script>

  <script id="ember913" class="ember-view" type="application/ld+json">{
  "@type": "BlogPosting",
  "headline": "LiveView Native Yearly Update",
  "description": "First LiveView Native update of 2023!",
  "datePublished": "2023-01-17T16:30:00.921Z",
  "publisher": {
    "@type": "Corporation",
    "name": "DockYard",
    "url": "https://dockyard.com",
    "legalName": "DockYard, Inc."
  },
  "mainEntityOfPage": "https://dockyard.com/blog",
  "genre": [
    "Engineering",
    "Elixir",
    "Mobile"
  ],
  "url": "https://dockyard.com/blog/2023/01/17/liveview-native-yearly-update",
  "author": {
    "@type": "Person",
    "name": "Brian Cardarella"
  },
  "@context": "http://schema.org"
}
</script>
```

Verifier: https://validator.schema.org/#url=https%3A%2F%2Fdockyard.com%2Fblog%2F2023%2F01%2F17%2Fliveview-native-yearly-update

**Comment by AZholtkevych** [comment]
@bcardarella is it possible to postpone this to Q2 as well? Thanks a lot

**Comment by bcardarella** [comment]
@AZholtkevych this is necessary for dockyard.com launch.

I think this lib can help: https://github.com/rdf-elixir/jsonld-ex

**Comment by leandrocp** [comment]
Search engines parse structured data to better understand each page in order to categorize a site and display rich results. There are different ways to add such data to pages and we'll use JSON-LD that is recommended by Google.

Working with structured data will be split into 2 parts:
- data structure, storage, and rendering
- admin UI to manage such data and validation

This issue covers the first part only.

## Data Structure and Storage

Let's keep it as simple as possible. We'll add a `:jsonb` column `data_structure` to `beacon_pages` to store that data:

Given this ld-json schema:

```json
    [{
      "@context": "https://schema.org/",
      "@type": "Recipe",
      "name": "Banana Bread Recipe",
      "description": "The best banana bread recipe you'll ever find! Learn how to use up all those extra bananas."
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Recipes",
        "item": "https://example.com/recipes"
      },{
        "@type": "ListItem",
        "position": 2,
        "name": "Bread recipes",
        "item": "https://example.com/recipes/bread-recipes"
      },{
        "@type": "ListItem",
        "position": 3,
        "name": "How To Make Banana Bread"
      }]
    }]
```

In Elixir it will look like:

```elixir
[
  %{
    "@context" => "https://schema.org/",
    "@type" => "Recipe",
    "name" => "Banana Bread Recipe"
    # ... omitted for brevity
  },
  %{
    "@context" => "https://schema.org",
    "@type" => "BreadcrumbList",
    "itemListElement" => [
      %{
        "@type" => "ListItem",
        "item" => "https://example.com/recipes",
        "name" => "Recipes",
        "position" => 1
      }
      # ... omitted for brevity
    ]
  }
]
```

And rendered inside `<head>` as:

```html
    <script type="application/ld+json">
    [{
      "@context": "https://schema.org/",
      "@type": "Recipe",
      "name": "Banana Bread Recipe",
      "description": "The best banana bread recipe you'll ever find! Learn how to use up all those extra bananas."
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [{
        "@type": "ListItem",
        "position": 1,
        "name": "Recipes",
        "item": "https://example.com/recipes"
      },{
        "@type": "ListItem",
        "position": 2,
        "name": "Bread recipes",
        "item": "https://example.com/recipes/bread-recipes"
      },{
        "@type": "ListItem",
        "position": 3,
        "name": "How To Make Banana Bread"
      }]
    }]
    </script>
```

So it'll be stored as the original json without transformations, which is simple and flexible to support [multiple items](https://developers.google.com/search/docs/appearance/structured-data/sd-policies#multiple-items)

## Rendering

It should be similar to [rendering meta tags](https://github.com/BeaconCMS/beacon/blob/7790eb72769a026c0bdfc3167aab394a9b73ce91/lib/beacon_web/components/layouts.ex#L99) but without the `DataSource` hook. Fetch from page and render.

## Notes
- We won't validate the content at this moment

## Refs
- https://www.w3.org/TR/json-ld/
- https://schema.org
- https://moz.com/blog/json-ld-for-beginners
- https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data
- https://search.google.com/test/rich-results
- https://json-ld.org
- https://github.com/garmeeh/next-seo#json-ld
