### ISSUE TITLE
Route Helpers - Verified route `~p`

### ISSUE THREAD

**Issue by TheFirstAvenger** [BeaconCMS/beacon#18]
We need to determine if we will be providing some sort of route helper in Beacon, and if so what it would look like.

**Comment by feliperenan** [comment]
How do you see this router helper working? Would it be some kind of sugar for defining routes in the `router` file? :thiking:

Also, At the moment Beacon doesn't allow developers to dynamically router their sites because we are using `live_session` which require routes to be defined at compile time.

What if we advice this pattern here for dinamic routes instead:

```elixir
scope "/sites/", BeaconWeb do
  pipe_through :browser
  pipe_through :beacon

  live_session :beacon do
    live "/:beacon_site/*path", PageLive, :path
  end
end
```

This only require Beacon to pattern match against it on [PageLive](https://github.com/BeaconCMS/beacon/blob/main/lib/beacon_web/live/page_live.ex#L6):

```elixir
def mount(%{"path" => path, "beacon_site" => site} = params, _session, socket) do
  ...
end
```

We might as well can use https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#on_mount/1 to enforce some stuff if needed on LV mount - such as full redirects among different pages. 

Wdyt @TheFirstAvenger?

**Comment by TheFirstAvenger** [comment]
The helpers would be similar to the Phoenix ones such as `Routes.dashboard_path(@conn, :index)`. Interestingly enough, I just saw [this feature](https://github.com/phoenixframework/phoenix/blob/master/CHANGELOG.md#introduction-of-verified-routes) in Phoenix 1.7, we might be able to implement something similar to this.
